spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab2dev
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  environment: development
#mvn spring-boot:run "-Dspring-boot.run.profiles=dev"
