app:
  datasource:
    url: jdbc:mysql://localhost:3306/lab2prod
    username: root
    password: MIR.una0745089308
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: ${app.datasource.driver-class-name}
#mvn clean package
#java -jar target/Lab2-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

#http://localhost:8081/actuator/info